receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:4317"
      http:
        endpoint: "localhost:4318"

exporters:
  logging:
  awsxray:
  awsemf:
    log_group_name: 'ADOTLogGroup'
    log_stream_name: 'ADOTLogStream'
    namespace: 'ADOTMetricNS'
    dimension_rollup_option: 1
    log_retention: 60

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging,awsxray]
    metrics:
      receivers: [otlp]
      exporters: [logging,awsemf]
  telemetry:
    metrics:
      address: localhost:8888
