AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Example template for an HTTP API that creates, updates, and deletes
  items in DynamoDB

  '
Globals:
  Function:
    Timeout: 10
    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  DDBHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: DDBHandlerFunction
      Handler: app.handler
      Runtime: nodejs18.x
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: ItemsTable
      Environment:
        Variables:
          NODE_OPTIONS: --require otel
      Events:
        GetAllItems:
          Type: HttpApi
          Properties:
            Path: /items
            Method: GET
        GetAnItem:
          Type: HttpApi
          Properties:
            Path: /items/{id}
            Method: GET
        DeleteAnItem:
          Type: HttpApi
          Properties:
            Path: /items/{id}
            Method: DELETE
        CreateOrUpdateItem:
          Type: HttpApi
          Properties:
            Path: /items
            Method: PUT
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.DDBHandlerFunctionbd7332faDepLayer
    Metadata:
      SamResourceId: DDBHandlerFunction
  ItemsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      TableName: http-crud-tutorial-items
  AwsSamAutoDependencyLayerNestedStack:
    DeletionPolicy: Delete
    Metadata:
      CreatedBy: AWS SAM CLI sync command
    Properties:
      TemplateURL: /home/houssam/Workspace/aws/aws-sam/otel-nodejs-demo/commonjs/.aws-sam/auto-dependency-layer/adl_nested_template.yaml
    Type: AWS::CloudFormation::Stack
Outputs:
  ApiEndpoint:
    Description: The invoke URL for our HTTP API
    Value:
      Fn::Sub: https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/items
  Function:
    Description: DynamoDB handler function ARN
    Value:
      Fn::GetAtt:
      - DDBHandlerFunction
      - Arn
